Fixes attribute error due to bad arg name
Fixes:

AttributeError: 'Namespace' object has no attribute 'infile_type'

which is caused by using `-` in positional argument names. Using the `metavar` keyword fixes this. See: https://stackoverflow.com/a/20250435